[project]
name = "camera_calibration"
version = "0.1.0"
description = "A research project on the use of artificial neural networks for camera calibration"
authors = [
    {name = "Dominik Babiarczyk", email = "dominik.babiarczyk1@gmail.com"},
]
dependencies = [
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "matplotlib>=3.10.8",
    "pandas>=2.2",
    "torch>=2.0",
    "torchvision>=0.15",
    "ipykernel>=6.29",
    "pyyaml>=6.0",
    "tqdm>=4.66",
]

requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
